org.gradle.jvmargs=-Xmx4G
android.useAndroidX=true
android.enableJetifier=true

# aumenta la JVM de gradle (6 GB). Si tu máquina tiene menos RAM usa 2g o 3g.
org.gradle.jvmargs=-Xmx6g -Xms512m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8

# mayor número de trabajadores si tienes CPU/RAM suficientes (opcional)
org.gradle.workers.max=6

# opciones para el daemon de Kotlin (mejora compilación Kotlin)
kotlin.daemon.jvm.options=-Xmx1536m