import 'package:flutter/material.dart';

ThemeData lightMode = ThemeData(
  useMaterial3: true,
  brightness: Brightness.light,
  colorScheme: ColorScheme.light(
    primary: const Color.fromRGBO(78, 101, 245, 1),
    onPrimary: Colors.black,
    secondary: const Color.fromRGBO(246, 199, 62, 1),
    onSecondary: Colors.black,
    tertiary: const Color.fromRGBO(135, 105, 83, 1),
    onTertiary: Colors.black,
    primaryContainer: Colors.white,
    onPrimaryContainer: Colors.black,
    secondaryContainer: Color.fromRGBO(76, 26, 221, 1),
    onSecondaryContainer: Colors.black,
    tertiaryContainer: const Color.fromRGBO(78, 101, 245, 1),
    onTertiaryContainer: Colors.black,
    surface: Colors.white,
    onSurface: Colors.black,
    surfaceBright: const Color.fromRGBO(242, 242, 247, 1),
    surfaceDim: const Color.fromRGBO(229, 229, 234, 1),
    surfaceContainerLowest: const Color.fromRGBO(209, 209, 214, 1),
    surfaceContainerLow: const Color.fromRGBO(199, 199, 204, 1),
    surfaceContainer: const Color.fromRGBO(174, 174, 178, 1),
    surfaceContainerHigh: const Color.fromRGBO(142, 142, 147, 1),
  ),
);

ThemeData darkMode = ThemeData(
  useMaterial3: true,
  brightness: Brightness.dark,
  colorScheme: ColorScheme.dark(
    primary: const Color.fromRGBO(78, 101, 245, 1),
    onPrimary: Colors.black,
    secondary: const Color.fromRGBO(135, 105, 83, 1),
    onSecondary: Colors.black,
    tertiary: const Color.fromRGBO(246, 199, 62, 1),
    onTertiary: Colors.black,
    primaryContainer: const Color.fromRGBO(28, 28, 30, 1),
    onPrimaryContainer: Colors.white,
    secondaryContainer: Color.fromRGBO(76, 26, 221, 1),
    onSecondaryContainer: Colors.black,
    tertiaryContainer: const Color.fromRGBO(78, 101, 245, 1),
    onTertiaryContainer: Colors.black,
    surface: Colors.black,
    onSurface: Colors.white,
    surfaceContainerHigh: const Color.fromRGBO(28, 28, 30, 1),
    surfaceContainer: const Color.fromRGBO(44, 44, 46, 1),
    surfaceContainerLow: const Color.fromRGBO(58, 58, 60, 1),
    surfaceContainerLowest: const Color.fromRGBO(72, 72, 74, 1),
    surfaceDim: const Color.fromRGBO(99, 99, 102, 1),
    surfaceBright: const Color.fromRGBO(144, 144, 147, 1),
  ),
);
