import 'package:flutter/material.dart';

ThemeData lightMode = ThemeData(
  useMaterial3: true,
  brightness: Brightness.light,
  colorScheme: ColorScheme.light(
    primary: const Color.fromRGBO(78, 101, 245, 1),
    onPrimary: Colors.black,
    secondary: const Color.fromRGBO(135, 105, 83, 1),
    onSecondary: Colors.black,
    tertiary: const Color.fromRGBO(246, 199, 62, 1),
    onTertiary: Colors.black,
    primaryContainer: Colors.white,
    onPrimaryContainer: Colors.black,
    secondaryContainer: const Color.fromRGBO(78, 101, 245, 1),
    onSecondaryContainer: Colors.black,
    tertiaryContainer: Color.fromRGBO(76, 26, 221, 1),
    onTertiaryContainer: Colors.black,
    surface: Colors.white,
    onSurface: Colors.black,
    surfaceBright: const Color.fromRGBO(252, 252, 254, 1),
    surfaceDim: const Color.fromRGBO(245, 245, 250, 1),
    surfaceContainerLowest: const Color.fromRGBO(240, 240, 245, 1),
    surfaceContainerLow: const Color.fromRGBO(235, 235, 240, 1),
    surfaceContainer: const Color.fromRGBO(215, 215, 220, 1),
    surfaceContainerHigh: const Color.fromRGBO(250, 250, 250, 1),
    errorContainer: Colors.orange,
  ),
);

ThemeData darkMode = ThemeData(
  useMaterial3: true,
  brightness: Brightness.dark,
  colorScheme: ColorScheme.dark(
    primary: const Color.fromRGBO(78, 101, 245, 1),
    onPrimary: Colors.black,
    secondary: const Color.fromRGBO(135, 105, 83, 1),
    onSecondary: Colors.black,
    tertiary: const Color.fromRGBO(246, 199, 62, 1),
    onTertiary: Colors.black,
    primaryContainer: const Color.fromRGBO(28, 28, 30, 1),
    onPrimaryContainer: Colors.white,
    secondaryContainer: const Color.fromRGBO(78, 101, 245, 1),
    onSecondaryContainer: Colors.black,
    tertiaryContainer: Color.fromRGBO(76, 26, 221, 1),
    onTertiaryContainer: Colors.black,
    surface: Colors.black,
    onSurface: Colors.white,
    surfaceContainerHigh: const Color.fromRGBO(28, 28, 30, 1),
    surfaceContainer: const Color.fromRGBO(44, 44, 46, 1),
    surfaceContainerLow: const Color.fromRGBO(58, 58, 60, 1),
    surfaceContainerLowest: const Color.fromRGBO(72, 72, 74, 1),
    surfaceDim: const Color.fromRGBO(99, 99, 102, 1),
    surfaceBright: const Color.fromRGBO(144, 144, 147, 1),
    errorContainer: Colors.orange,
  ),
);
